local currentDir = fs.getDir(shell.getRunningProgram())
local parentDir = fs.getDir(currentDir)
shell.setDir(parentDir)
shell.run("github clone PapaSmurfDev/HeadsUpDisplayLogger")
shell.setDir(currentDir)
print("You may now implement displayLogger into your script with DisplayLogger")
print("Remember to use a overlay glasses for the neural interface")
